version: '3'
services:
  web:
    build: flask
    ports:
      - '5002:5000'
    environment:
      - FLASK_ENV=development
      - MYSQL_ROOT_PASSWORD=p@ssw0rd1
    networks:
      - mynet
      - mynet2
  mysqldb:
    image: mysql:latest
    ports: 
      - '3316:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd1
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    networks:
      - mynet2
volumes:
  mysql:
    driver: local
  mysql_config:
    driver: local
networks:
  mynet:
    driver: bridge
  mynet2:
    driver: bridge